package theknife.common.enums;

/**
 * Rappresenta i tipi di comandi che possono essere inviati dal client al server.
 *
 * @author Gasparini Lorenzo, 759929, VA
 */

public enum CommandType { 
//TUTTI
CERCA_RISTORANTI, OTTIENI_DETTAGLI_RISTORANTE, LEGGI_RECENSIONI, CERCA_VICINO,
// OSPITE 
OTTIENI_LOCALITA_INIZIALE, ACCEDI, REGISTRATI,
// CLIENTE 
AGGIUNGI_PREFERITO, RIMUOVI_PREFERITO, VEDI_PREFERITI, AGGIUNGI_RECENSIONE, MODIFICA_RECENSIONE, 
ELIMINA_RECENSIONE,
// RISTORATORE 
AGGIUNGI_RISTORANTE, VEDI_RISTORANTI_GESTITI, LEGGI_RECENSIONI_RISTORANTI_GESTITI, 
OTTIENI_STATISTICHE_RISTORANTE, RISPONDI_RECENSIONE, ASSOCIA_RISTORANTE,
// CLIENTE E RISTORATORE
ESCI
}

